language: node_js

node_js:
  - "0.10"
  # jsdom fails with error here.
  #- "0.12"

sudo: false

branches:
  only:
    - master

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm run check-ci
  - npm run test-frontend-sauce

  # Manually send coverage reports to coveralls.
  # - Aggregate client results
  # - Single server results
  - ls  coverage/client/*/lcov.info coverage/server/lcov.info | cat
  - cat coverage/client/*/lcov.info coverage/server/lcov.info | node_modules/.bin/coveralls || echo "Coveralls upload failed"

  # Try a build of the docs and such
  - npm run build

env:
  global:
    - secure: GUzDAvlbRX+xII7nNDzGw72XDz2GX3b4tGwZiV/LR3N+oWQMR7Kv4D8p4x/K9RR2NVgYvWc4EW1NHF/X28B7SWnxFH2W8znteyx6cyV2InVmAUAUMXP5sW4msEN/tQuEusyzkzm9me5n8uHPGbkm6g30bmyEB8+NE3lQgQk3B8w=
    - secure: So1D+mAFc3HhlZqskQ+Dft4T4BjzQIuIbW4gl/y5R3THd8qwaV9R5KJCo0hz+b+X/ThuerOlgN1xPk0Y66mwExsV2JhvRH+l3R+ALlIat4YZiy7EBnJ9cqjUHA1NdY56dJr3MQ8Ce6O0YaROts9TY12ml88MhGXdMW7sMIwYPg0=
